
-- ZIPCODE_INFO TABLE
ALTER TABLE ZIPCODE_INFO
ALTER COLUMN CITY VARCHAR2(25);

ALTER TABLE ZIPCODE_INFO
ADD STATE VARCHAR2(2);
GO

-- INSTRUCTOR_INFO TABLE
ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR2(25);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR2(25);

ALTER TABLE INSTRUCTOR_INFO
ADD 
    STREET_ADDRESS VARCHAR2(50),
    ZIP_CODE VARCHAR2(5);
GO

-- COURSE_INFO TABLE
ALTER TABLE COURSE_INFO
ALTER COLUMN COST NUMERIC(9,2);

ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR2(50),
    COURSE_PREREQUISITE NUMERIC(8,0);
GO

-- STUDENT_INFO TABLE
ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME VARCHAR2(25);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME VARCHAR2(25);

ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR2(50),
    ZIP_CODE VARCHAR2(5);
GO

-- SECTION_INFO TABLE
ALTER TABLE SECTION_INFO
ALTER COLUMN SECTION_NO NUMERIC(3,0);

ALTER TABLE SECTION_INFO
ADD 
    LOCATION VARCHAR(50),
    CAPACITY NUMERIC(3,0);
GO

-- ENROLLMENT_INFO TABLE
ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;
GO

-- GRADE_INFO TABLE
ALTER TABLE GRADE_INFO
ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0);

ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0);
GO
