
-- ZIPCODE_INFO TABLE 
ALTER TABLE ZIPCODE_INFO
ADD 
    CONSTRAINT ZIP_PK PRIMARY KEY (ZIP_CODE),
    CONSTRAINT ZIP_CITY_NN CHECK(CITY IS NOT NULL),
    CONSTRAINT ZIP_STATE_NN CHECK(STATE IS NOT NULL);
GO

-- INSTRUCTOR_INFO TABLE 
ALTER TABLE INSTRUCTOR_INFO
ADD
    CONSTRAINT INSTRUCTOR_ID_PK PRIMARY KEY(INSTRUCTOR_ID),
    CONSTRAINT INSTRUCTOR_FN_NN CHECK(INSTRUCTOR_FIRST_NAME IS NOT NULL),
    CONSTRAINT INSTRUCTOR_LN_NN CHECK(INSTRUCTOR_LAST_NAME IS NOT NULL),
    CONSTRAINT ZIP_INSTRUCTOR_FK FOREIGN KEY(ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);
GO

-- COURSE_INFO TABLE 
ALTER TABLE COURSE_INFO
ADD
    CONSTRAINT COURSE_NO_PK PRIMARY KEY(COURSE_NO),
    CONSTRAINT COURSE_NAME_NN CHECK(COURSE_NAME IS NOT NULL),
    CONSTRAINT COST_NN CHECK(COST IS NOT NULL);
GO

-- STUDENT_INFO TABLE 
ALTER TABLE STUDENT_INFO
ADD
    CONSTRAINT STUDENT_ID_PK PRIMARY KEY(STUDENT_ID),
    CONSTRAINT STUDENT_FN_NN CHECK(STUDENT_FIRST_NAME IS NOT NULL),
    CONSTRAINT STUDENT_LN_NN CHECK(STUDENT_LAST_NAME IS NOT NULL),
    CONSTRAINT ZIP_STUDENT_FK FOREIGN KEY(ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);
GO


-- SECTION_INFO TABLE 
ALTER TABLE SECTION_INFO
ADD
    CONSTRAINT SECTION_ID_PK PRIMARY KEY(SECTION_ID),
    CONSTRAINT COURSE_SECTION_FK FOREIGN KEY(COURSE_NO) REFERENCES COURSE_INFO(COURSE_NO),
    CONSTRAINT SECTION_NO_NN FOREIGN KEY(SECTION_NO) REFERENCES SECTION_INFO(SECTION_NO),
    CONSTRAINT INSTRUCTOR_SECTION_FK FOREIGN KEY(INSTRUCTOR_ID) REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID);
GO

-- ENROLLMENT_INFO TABLE 
ALTER TABLE ENROLLMENT_INFO
ADD
    CONSTRAINT ENROLLMENT_STUD_SECT_PK PRIMARY KEY (STUDENT_ID,SECTION_ID),
    CONSTRAINT ENROLLMENT_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    CONSTRAINT ENROLLMENT_SECTION_ID_FK FOREIGN KEY(SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID);
GO



-- GRADE_INFO TABLE 
ALTER TABLE GRADE_INFO
ADD
    CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK PRIMARY KEY(STUDENTID, SECTIONID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE),
    CONSTRAINT GRADE_STUDENT_ID_FK FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    CONSTRAINT GRADE_SECTION_ID_FK FOREIGN KEY(SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID),
    CONSTRAINT CHK_GRADE_TYPE_CODE CHECK (GRADE_TYPE_CODE IN ('FI', 'HM', 'MT', 'PA', 'PJ', 'QZ')),
    CONSTRAINT NUMERIC_GRADE_NN DEFAULT 0 FOR NUMERIC_GRADE;
GO